language: go

go:
  - 1.4
  - 1.5
  - 1.6
  - tip

script:
  - go get github.com/PlanitarInc/go-workers
  - go get github.com/jteeuwen/go-bindata
  - go get github.com/gocql/gocql
  - go get github.com/onsi/gomega
  - make
  - go test -v

services:
  - redis-server
